const items = [
    {
        name: "hello",
        category: "ring",
        itemNumber: "#101",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: '/images/rings/ring3.png',
        staus: "Sold",
        price: 9.99,
        images: [
            { images: "/images/rings/ring3.png" },
            { images: "/images/rings/ring3.png" },
            { images: '/images/rings/ring3.png' },
            { images: "/images/rings/ring3.png" }
        ]
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#102",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring2.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#103",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: '/images/bracelet/bracelet2.png',
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#104",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring1.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#105",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring2.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#106",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/bracelet/bracelet1.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#107",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: '/images/rings/ring1.png',
        staus: "Sold",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#108",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring2.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#109",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: '/images/bracelet/bracelet2.png',
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#110",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring1.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#111",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring2.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#112",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/bracelet/bracelet1.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#113",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: '/images/rings/ring1.png',
        staus: "Sold",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#114",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring2.png",
        staus: "Stock",
        price: 9.99,

    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#115",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: '/images/bracelet/bracelet2.png',
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#116",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring1.png",
        staus: "Stock",
        price: 5,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#117",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring2.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#118",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/bracelet/bracelet1.png",
        staus: "Stock",
        price: 10,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#119",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: '/images/rings/ring1.png',
        staus: "Sold",
        price: 11.29,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#120",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring2.png",
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#121",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: '/images/bracelet/bracelet2.png',
        staus: "Stock",
        price: 9.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#122",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring1.png",
        staus: "Stock",
        price: 10,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#123",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/rings/ring2.png",
        staus: "Stock",
        price: 4.99,
    },
    {
        name: "hello",
        category: "ring",
        itemNumber: "#124",
        description: "cbdbsck cndknckd dcnkdnc ,cnkjdwnc ",
        image: "/images/bracelet/bracelet1.png",
        staus: "Stock",
        price: 9.99,
    },
]

export { items }